-- MySQL Script generated by MySQL Workbench
-- Sat Apr 11 15:00:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tp_assignment3_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tp_assignment3_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tp_assignment3_db` DEFAULT CHARACTER SET utf8 ;
USE `tp_assignment3_db` ;

-- -----------------------------------------------------
-- Table `tp_assignment3_db`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_assignment3_db`.`client` (
  `idclient` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  PRIMARY KEY (`idclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp_assignment3_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_assignment3_db`.`products` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_name` varchar(45) DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `price` float DEFAULT NULL,
  PRIMARY KEY (`id`)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp_assignment3_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_assignment3_db`.`orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(45) NULL,
  `order_quantity` INT NULL,
  PRIMARY KEY (`idorders`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
